# Generated by Django 3.1.5 on 2021-01-10 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('gender', models.IntegerField(choices=[(0, 'Homem'), (1, 'Mulher')], verbose_name='Sexo')),
                ('latitude', models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)])),
                ('longitude', models.FloatField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)])),
                ('infected', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='Infectado')),
                ('fiji_water', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possuí água de Fiji')),
                ('campbell_soup', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possuí sopa')),
                ('first_aid_pouch', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possuí Med kit')),
                ('ak47', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possuí AK47')),
            ],
        ),
    ]
